default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: currency_development
test:
  <<: *default
  database: currency_test

production:
  <<: *default
  database: currency_production
